version: "3.9"

services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: always
    command: >
      sh -c "until pg_isready -h db -p 5432; do echo 'Waiting for Postgres...'; sleep 2; done &&
             goose -dir $GOOSE_MIGRATION_DIR $GOOSE_DRIVER \"$GOOSE_DBSTRING\" up &&
             ./build/server"

volumes:
  postgres_data:
